version: 2

sources:
    - name: staging
      database: dtc-gcp-339512
      schema: trips_data_all
      tables:
        - name: external_green_tripdata
        - name: external_yellow_tripdata

        