
# First-time build can take upto 10 mins.

FROM apache/airflow:2.2.3


ENV AIRFLOW_HOME=/opt/airflow

USER root
RUN apt-get update -qq && apt-get install vim -qqq
# git gcc g++ -qqq

COPY requirements-local.txt .
RUN pip install --no-cache-dir -r requirements-local.txt

# Ref: https://airflow.apache.org/docs/docker-stack/recipes.html

SHELL ["/bin/bash", "-o", "pipefail", "-e", "-u", "-x", "-c"]

#DK_VERSION=322.0.0
#HOME=/home/google-cloud-sdk
#
#{GCLOUD_HOME}/bin/:${PATH}"
#
#D_URL="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz" \
#DIR="$(mktemp -d)" \
# -fL "${DOWNLOAD_URL}" --output "${TMP_DIR}/google-cloud-sdk.tar.gz" \
#r -p "${GCLOUD_HOME}" \
#xzf "${TMP_DIR}/google-cloud-sdk.tar.gz" -C "${GCLOUD_HOME}" --strip-components=1 \
#CLOUD_HOME}/install.sh" \
#sh-completion=false \
#th-update=false \
#age-reporting=false \
#       --quiet \
#    && rm -rf "${TMP_DIR}" \
#    && gcloud --version

WORKDIR $AIRFLOW_HOME

USER $AIRFLOW_UID
